# -*- coding: utf-8 -*-
"""Código POO - VoAgro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mgaVTZo_qeh-tYWZyl3pEDgVB1AXbnn2

# **Projeto de POO - VoAgro**

#5.   Classe Application: """

class Application:
    def __init__(self, bg_img_path, server):
        self.bg_image = cv2.imread(bg_img_path)
        self.grid = None # Placeholder line

        self.inferences []
        self.server = server
        self.socket = create_socket(self.server) # Placeholder line
        
        draw_interface()

    def draw_interface(self): # WIP
        pass
    
    def set_connection(self):
        self.socket.connect # Placeholder line
    
    def receive_data(self):
        success, data = self.socket.buffer_read() # Placeholder line
        if success == True:
            self.inferences.extend(data)
        else:
            print("Buffer_read unsuccessful. No data read.")
    
    def draw_inferences(self):
        for inference in self.inferences: # Placeholder block
            draw_on_screeen(inferene)
    
    def update(self): # WIP
        pass
